#!/bin/sh
if [ -f Makefile ]; then
	# Make qTip2 with all plugins, and a basic version with none
	make all
	make PLUGINS="None" QTIP="dist/jquery.qtip.basic.js" qtip

	# Re-add dist folder
	git add dist/*
fi	
